spring:
  application:
    name: demo-user
  datasource:
    url: jdbc:mysql://localhost:3306/user-db?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret: ${JWT_SECRET}
  expiration-millis: 28800000

security:
  permittedPaths:
    - "/auth/**"
  cors-allowed-origins:
    - "http://localhost:8085"
  cors-allowed-methods:
    - "GET"
    - "POST"
  cors-allowed-headers:
    - "Authorization"
    - "Content-Type"
  cors-allowed-paths:
    - "/**"

async-config:
  thread-pool:
    core-pool-size: 2
    max-pool-size: 2
    queue-capacity: 500
    thread-name-prefix: "UserProjectAsyncThread-"